package com.alpermulayim.openfoodfacts_spring_boot_starter.dtos;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public record Product (
    @JsonProperty("abbreviated_product_name") String abbreviatedProductName,
    @JsonProperty("code") String code,
    @JsonProperty("codes_tags") List<String> codesTags,
    @JsonProperty("generic_name") String genericName,
    @JsonProperty("id") String id,
    @JsonProperty("lc") String lc,
    @JsonProperty("lang") String lang,
    @JsonProperty("nova_group") Integer novaGroup,
    @JsonProperty("nova_groups") String novaGroups,
    @JsonProperty("obsolete") String obsolete,
    @JsonProperty("obsolete_since_date") String obsoleteSinceDate,
    @JsonProperty("product_name") String product_name,
    @JsonProperty("product_name_en") String productNameEn,
    @JsonProperty("product_quantity") String productQuantity,
    @JsonProperty("product_quantity_unit") String productQuantityUnit,
    @JsonProperty("quantity") String quantity,
    @JsonProperty("additives_n") Integer additivesN,
    @JsonProperty("checked") String checked,
    @JsonProperty("complete") Integer complete,
    @JsonProperty("completeness") Double completeness,
    @JsonProperty("ecoscore_grade") String ecoscoreGrade,
    @JsonProperty("ecoscore_score") Integer ecoscoreScore,
    @JsonProperty("food_groups") String foodGroups,
    @JsonProperty("food_groups_tags") List<String> foodGroupsTags,
    @JsonProperty("nutrient_levels") NutrientLevels nutrientLevels,
    @JsonProperty("packaging_text") String packagingText,
    @JsonProperty("packagings") List<Packaging> packagings,
    @JsonProperty("packagings_complete") Integer packagingsComplete,
    @JsonProperty("pnns_groups_1") String pnnsGroups1,
    @JsonProperty("pnns_groups_1_tags") List<String> pnnsGroups1Tags,
    @JsonProperty("pnns_groups_2") String pnnsGroups2,
    @JsonProperty("pnns_groups_2_tags") List<String> pnnsGroups2Tags,
    @JsonProperty("popularity_key") Long popularityKey,
    @JsonProperty("popularity_tags") List<String> popularityTags,
    @JsonProperty("scans_n") Integer scansN,
    @JsonProperty("unique_scans_n") Integer uniqueScansN,
    @JsonProperty("serving_quantity") String servingQuantity,
    @JsonProperty("serving_quantity_unit") String servingQuantityUnit,
    @JsonProperty("serving_size") String servingSize,
    @JsonProperty("brands") String brands,
    @JsonProperty("brands_tags") List<String> brandsTags,
    @JsonProperty("categories") String categories,
    @JsonProperty("categories_hierarchy") List<String> categoriesHierarchy,
    @JsonProperty("categories_lc") String categoriesLc,
    @JsonProperty("categories_tags") List<String> categoriesTags,
    @JsonProperty("checkers_tags") List<String> checkersTags,
    @JsonProperty("cities") String cities,
    @JsonProperty("cities_tags") List<String> citiesTags,
    @JsonProperty("correctors_tags") List<String> correctorsTags,
    @JsonProperty("countries") String countries,
    @JsonProperty("countries_hierarchy") List<String> countriesHierarchy,
    @JsonProperty("countries_lc") String countriesLc,
    @JsonProperty("countries_tags") List<String> countriesTags,
    @JsonProperty("ecoscore_tags") List<String> ecoscoreTags,
    @JsonProperty("emb_codes") String embCodes,
    @JsonProperty("emb_codes_orig") String embCodesOrig,
    @JsonProperty("emb_codes_tags") List<String> embCodesTags,
    @JsonProperty("labels") String labels,
    @JsonProperty("labels_hierarchy") List<String> labelsHierarchy,
    @JsonProperty("labels_lc") String labelsLc,
    @JsonProperty("labels_tags") List<String> labelsTags,
    @JsonProperty("entry_dates_tags") List<String> entryDatesTags,
    @JsonProperty("manufacturing_places") String manufacturingPlaces,
    @JsonProperty("manufacturing_places_tags") List<String> manufacturingPlacesTags,
    @JsonProperty("nova_groups_tags") List<String> novaGroupsTags,
    @JsonProperty("nutrient_levels_tags") List<String> nutrientLevelsTags,
    @JsonProperty("last_image_dates_tags") List<String> lastImageDatesTags,
    @JsonProperty("last_image_t") Integer lastImageT,
    @JsonProperty("selected_images") Map<String, SelectedImages> selectedImages,
    @JsonProperty("image_small_url") String imageSmallUrl,
    @JsonProperty("image_thumb_url") String imageThumbUrl,
    @JsonProperty("image_url") String imageUrl,
    @JsonProperty("ecoscore_data") EcoscoreData ecoscoreData,
    @JsonProperty("agribalyse") Agribalyse agribalyse,
    @JsonProperty("grade") String grade,
    @JsonProperty("grades") Map<String, String> grades,
    @JsonProperty("missing") Missing missing,
    @JsonProperty("missing_data_warning") Integer missingDataWarning,
    @JsonProperty("previous_data") PreviousData previousData,
    @JsonProperty("score") Integer score,
    @JsonProperty("scores") Map<String, Integer> scores,
    @JsonProperty("status") String status,
    @JsonProperty("ecoscore_extended_data_version") String ecoscoreExtendedDataVersion,
    @JsonProperty("environment_impact_level") String environmentImpactLevel,
    @JsonProperty("environment_impact_level_tags") List<String> environmentImpactLevelTags,
    @JsonProperty("additives_tags") List<String> additivesTags,
    @JsonProperty("allergens") String allergens,
    @JsonProperty("allergens_lc") String allergensLc,
    @JsonProperty("allergens_hierarchy") List<String> allergensHierarchy,
    @JsonProperty("allergens_tags") List<String> allergensTags,
    @JsonProperty("ingredients") List<Ingredient> ingredients,
    @JsonProperty("ingredients_analysis") Map<String, List<String>> ingredientsAnalysis,
    @JsonProperty("ingredients_tags") List<String> ingredientsTags,
    @JsonProperty("ingredients_lc") String ingredientsLc,
    @JsonProperty("ingredients_text") String ingredientsText,
    @JsonProperty("ingredients_text_with_allergens") String ingredientsTextWithAllergens,
    @JsonProperty("ingredients_from_palm_oil_n") Integer ingredientsFromPalmOilN,
    @JsonProperty("ingredients_from_palm_oil_tags") List<String> ingredientsFromPalmOilTags,
    @JsonProperty("origins") String origins,
    @JsonProperty("origins_lc") String originsLc,
    @JsonProperty("origins_tags") List<String> originsTags,
    @JsonProperty("traces") String traces,
    @JsonProperty("traces_lc") String tracesLc,
    @JsonProperty("unknown_ingredients_n") Integer unknownIngredientsN,
    @JsonProperty("no_nutrition_data") String noNutritionData,
    @JsonProperty("nutriments") Nutriments nutriments,
    @JsonProperty("nutrition_grade_fr") String nutritionGradeFr,
    @JsonProperty("nutrition_grades") String nutritionGrades,
    @JsonProperty("nutrition_grades_tags") List<String> nutritionGradesTags,
    @JsonProperty("nutrition_score_beverage") Integer nutritionScoreBeverage,
    @JsonProperty("nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients") Integer nutritionScoreWarningFruitsVegetablesNutsEstimateFromIngredients,
    @JsonProperty("nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value") Integer nutritionScoreWarningFruitsVegetablesNutsEstimateFromIngredientsValue,
    @JsonProperty("nutrition_score_warning_no_fiber") Integer nutritionScoreWarningNoFiber,
    @JsonProperty("other_nutritional_substances_tags") List<String> otherNutritionalSubstancesTags,
    @JsonProperty("unknown_nutrients_tags") List<String> unknownNutrientsTags,
    @JsonProperty("vitamins_tags") List<String> vitaminsTags,
    @JsonProperty("nutriscore_2021") Nutriscore nutriscore2021,
    @JsonProperty("nutriscore_2023") Nutriscore nutriscore2023,
    @JsonProperty("nutriscore_data") NutriscoreData nutriscoreData,
    @JsonProperty("nutriscore_grade") String nutriscoreGrade,
    @JsonProperty("nutriscore_score") Integer nutriscoreScore,
    @JsonProperty("nutriscore_score_opposite") Integer nutriscoreScoreOpposite,
    @JsonProperty("nutriscore_tags") List<String> nutriscoreTags,
    @JsonProperty("nutriscore_version") String nutriscoreVersion,
    @JsonProperty("additives_original_tags") List<String> additivesOriginalTags,
    @JsonProperty("additives_prev_original_tags") List<String> additivesPrevOriginalTags,
    @JsonProperty("added_countries_tags") List<String> addedCountriesTags,
    @JsonProperty("allergens_from_ingredients") String allergensFromIngredients,
    @JsonProperty("allergens_from_user") String allergensFromUser,
    @JsonProperty("amino_acids_prev_tags") List<String> aminoAcidsPrevTags,
    @JsonProperty("amino_acids_tags") List<String> aminoAcidsTags,
    @JsonProperty("carbon_footprint_percent_of_known_ingredients") Integer carbonFootprintPercentOfKnownIngredients,
    @JsonProperty("categories_properties") CategoriesProperties categoriesProperties,
    @JsonProperty("categories_properties_tags") List<String> categoriesPropertiesTags,
    @JsonProperty("compared_to_category") String comparedToCategory,
    @JsonProperty("conservation_conditions") String conservationConditions,
    @JsonProperty("customer_service") String customerService,
    @JsonProperty("expiration_date") String expirationDate,
    @JsonProperty("link") String link,
    @JsonProperty("main_countries_tags") List<String> mainCountriesTags,
    @JsonProperty("minerals_prev_tags") List<String> mineralsPrevTags,
    @JsonProperty("minerals_tags") List<String> mineralsTags,
    @JsonProperty("owner_fields") OwnerFields ownerFields,
    @JsonProperty("nova_groups_markers") NovaGroupsMarkers novaGroupsMarkers,
    @JsonProperty("origin") String origin,
    @JsonProperty("purchase_places") String purchasePlaces,
    @JsonProperty("purchase_places_tags") List<String> purchasePlacesTags,
    @JsonProperty("stores") String stores,
    @JsonProperty("stores_tags") List<String> storesTags,
    @JsonProperty("traces_from_ingredients") String tracesFromIngredients,
    @JsonProperty("traces_from_user") String tracesFromUser,
    @JsonProperty("created_t") Integer createdT,
    @JsonProperty("creator") String creator,
    @JsonProperty("editors_tags") List<String> editorsTags,
    @JsonProperty("informers_tags") List<String> informersTags,
    @JsonProperty("interface_version_created") String interfaceVersionCreated,
    @JsonProperty("interface_version_modified") String interfaceVersionModified,
    @JsonProperty("languages") Map<String, Integer> languages,
    @JsonProperty("languages_codes") Map<String, Integer> languagesCodes,
    @JsonProperty("languages_hierarchy") List<String> languagesHierarchy,
    @JsonProperty("languages_tags") List<String> languagesTags,
    @JsonProperty("last_edit_dates_tags") List<String> lastEditDatesTags,
    @JsonProperty("last_editor") String lastEditor,
    @JsonProperty("last_modified_by") String lastModifiedBy,
    @JsonProperty("last_modified_t") Integer lastModifiedT,
    @JsonProperty("owner") String owner,
    @JsonProperty("owners_tags") String ownersTags,
    @JsonProperty("photographers_tags") List<String> photographersTags,
    @JsonProperty("rev") Integer rev,
    @JsonProperty("sources") List<Source> sources,
    @JsonProperty("sources_fields") Map<String, Object> sourcesFields,
    @JsonProperty("teams") String teams,
    @JsonProperty("teams_tags") List<String> teamsTags,
    @JsonProperty("update_key") String updateKey,
    @JsonProperty("knowledge_panels") KnowledgePanels knowledgePanels
) {}
